### PR TITLE
Adds ContactForm component to the site

### PR DESCRIPTION
**Pull request by WebInspectInc**
Addresses #7. I went with a Netlify form, just because it seemed the easiest and quickest solution. Untested as of yet, but I think we should be able to test it with the deploy preview. The copy on the page will also need to be updated, since we will now have a "fancy contact form" 🙂

### CODE REVIEW

**Comment by WebInspectInc** [comment]
Tested the form and it seems to submit properly. @MuffinTheMan can you see the submission in Netlify?

**Comment by WebInspectInc** [comment]
Added the issue number to the commit message. Didn't see that note in the readme until now :)

**Comment by MuffinTheMan** [comment]
@WebInspectInc I saw the message come through! Sweet!

**Comment by MuffinTheMan** [comment]
Page copy has been updated.

**Pull request merged**
